- name: Install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Install Repository Jenkins
  copy:
    src: jenkins.repo
    dest: /etc/yum.repos.d/
    
- name: Import key Repository
  command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start Jenkins
  service:
    name: jenkins
    state: started

- name: Stop Firewalld
  service:
    name: firewalld
    state: stopped
