- name: Install Lamp
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Install php
      yum:
        name: php
        state: latest

    - name: Install Mariadb
      yum:
        name: mariadb
        state: latest
