- name: Install Git
  yum:
    name: git
    state: latest

- name: Download Netdata
  command: git clone https://github.com/netdata/netdata.git --depth=100

- name: Install Netdata
  command: /root/netdata/netdata-installer.sh --install /opt --dont-wait
