- name: Install Git
  yum:
    name: git
    state: latest

- name: Install autotools
  yum:
    name: "@Development tools"
    state: latest

- name: Install libuuid-devel
  yum:
    name: libuuid-devel
    state: latest

- name: Install zlib-devel
  yum:
    name: zlib-devel
    state: latest

- name: Download Netdata
  command: git clone https://github.com/netdata/netdata.git --depth=100 /opt/netdata_git

- name: Install Netdata
  shell: /opt/netdata_git/netdata-installer.sh --install /opt --dont-wait
