- name: Include Rsyslog line
  lineinfile:
    path: /etc/rsyslog.conf
    line: *.* @192.168.131.15:5140
    create: yes

- name: Restart Rsyslog service
  service:
    name: rsyslog
    state: restarted
