- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Copy Repository
  copy:
    src: rundeck.repo
    dest: /etc/yum.repos.d/

- name: Install Rundeck
  yum:
    name: rundeck
    state: latest

- name: start rundeck
  command: service rundeckd start


sudo sed -i "s#localhost#`ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`#g" /etc/rundeck/rundeck-config.properties
