- name: Deploy server02
  hosts: all
  become: yes
  tasks:

    - include: playbooks/terraform.yml

    - include: playbooks/rundeck.yml

    - include: playbooks/netdata.yml

    - include: playbooks/rsyslog.yml

    - include: playbooks/cloud_sdk.yml

    - include: playbooks/stop_firewalld.yml
