- name: Deploy server03
  hosts: all
  become: yes
  tasks:

    - include: playbooks/lamp.yml

    - include: playbooks/netdata.yml

    - include: playbooks/rsyslog.yml

    - include: playbooks/stop_firewalld.yml
