- name: Deploy server04
  hosts: all
  become: yes
  tasks:

    - include: playbooks/docker.yml

    - include: playbooks/jenkins.yml

    - include: playbooks/netdata.yml

    - include: playbooks/rsyslog.yml

    - include: playbooks/stop_firewalld.yml
